### ISSUE TITLE
some properties of a manifest cannot be changed in boilerplates

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/coder-toolset#6]
### AS-IS
Since boilerplates use tools of the coder-toolset, the manifest of a webpackage is built using the `wpkg-utils` package. However, the `author`, `contributors`, `keywords`, `description`, `homepage`, `groupId`, `runnables`, `man` properties definition is hardcoded or absent in the [getManifestWebpackage](https://github.com/cubbles/coder-toolset/blob/develop/packages/wpkg-utils/lib/getManifestWebpackage.js) script and are inaccessible from a boilerplate (unless a coder modifies the code in the node_modules folder, which is undesirable).

### TO-BE
Use the definitions of the package.json file

**Comment by edwingamboa** [comment]
@hrbu @pwrinc @jtrs 
Besides the `author`, I identified other properties that can be defined in [package.json](https://docs.npmjs.com/files/package.json) file, which I think are important for the base (e.g. to find an artifact or webpackage): `contributors, keywords, description`.

Also, the `groupId `that is hardcoded in the [getManifestWebpackage](https://github.com/cubbles/coder-toolset/blob/develop/packages/wpkg-utils/lib/getManifestWebpackage.js) script. And the `runnables` property is not defined. **But those are not valid package.json properties**.

Finally, the `man` property should be a list of objects the [package.json](https://docs.npmjs.com/files/package.json#man) file and in a Cubbles manifest it should be a list of urls (strings).

Should we use the package.json to define the values of the properties for the first case? (I would say yes)
What should we do for the last two cases?

**Comment by hrbu** [comment]
> Should we use the package.json to define the values of the properties for the first case? (I would say yes)

I aggree.

> groupId ... man

I think we should extend the package.json by a `cubbles` entry (object) and provide in additional properties as properties of the `cubbles` object.

**Comment by edwingamboa** [comment]
A new version of the @cubbles/wpkg-utils was published: https://www.npmjs.com/package/@cubbles/wpkg-utils/v/0.1.2
