### ISSUE TITLE
The .cubblesignore file is not supported in boilerplates

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/coder-toolset#7]
### AS_IS
When uploading a webpackage a `.cubblesignore` file can be provided to avoid uploading undesired files to a base. That file should be located at the root folder of the webpackage. However, when using the vanilla boilerplate the webpackage is built on the fly. But if a `.cubblesignore` is provided this is not recognised.

### TO_BE
When a `.cubblesignore` file is at the root folder, this should be copied to the webpackage folder in the dist folder when running build commands.

**Comment by hrbu** [comment]
You are right. The question is, do we need it?
As we now have a dedicated .dist folder, we can control (via webpack config) what's in.

**Comment by edwingamboa** [comment]
I didn't think about it when I created the issue. But, since the files which are included in the dist folder are controlled via webpack, then a .cubblesignore file would not be needed. Should I close the issue? and maybe label it as invalid or as question.

**Comment by hrbu** [comment]
label as question and close it.



_____________________________________

Hans-Dieter Böhlau
Geschäftsführer, Softwarearchitekt

GETrequest GmbH
Bauhausstr. 7c
D-99423 Weimar

M +49 159 0167 5467<tel:+49%20159%200167%205467>
boehlau@getrequest.de<mailto:boehlau@getrequest.de>
https://getrequest.de

Handelsregister: Amtsgericht Jena, HRB 514462
Geschäftsführer: Hans-Dieter Böhlau, Philipp Wagner


-------- Original message --------
